##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

windowrule {
  name = workspace-2-browser
  match:class = brave-browser
  workspace = 2
}

windowrule {
  name = workspace-3-code-editor
  match:class = ^(code-oss|jetbrains-idea)$
  workspace = 3
}

windowrule {
  name = workspace-4-app
  match:class = ^(Minecraft.*|OxygenNotIncluded)
  workspace = 4
}

windowrule {
  name = workspace-5-app-console
  match:class = ^(PandoraLauncher|steam)$
  workspace = 5
}

windowrule {
  name = workspace-6-chat
  match:class = discord
  workspace = 6
}

windowrule {
  name = workspace-8-setting
  match:class = org.pulseaudio.pavucontrol
  match:class = system-config-printer
  workspace = 8
}

windowrule {
  name = workspace-9-password-manager
  match:class = KeePassXC
  workspace = 9
}

windowrule {
  name = transparent-apps-0.8
  match:class = ^(.*)$
  opacity = 0.8 0.8
}

windowrule {
  name = transparent-apps-1
  match:class = ^(Minecraft.*)$
  opacity = 1
}
